default_platform(:ios)

platform :ios do
  desc "Increment build number"
  lane :bump do
    increment_build_number(
      xcodeproj: "Runner.xcodeproj"
    )
  end

  desc "Build and distribute to Firebase App Distribution"
  lane :distribute do
    bump
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )
    firebase_app_distribution(
      app: "1:629899183939:ios:b121b5f2c5f3e3f3e3f3e3",
      testers: "test@example.com",
      firebase_cli_path: "/usr/local/bin/firebase"
    )
  end
end