default_platform(:android)

platform :android do
  desc "Increment version code"
  lane :bump do
    gradle(
      task: "incrementVersionCode",
      gradlew_path: "../../gradlew"
    )
  end

  desc "Build and distribute to Firebase App Distribution"
  lane :distribute do
    bump
    gradle(
      task: "app:assembleRelease"
    )
    firebase_app_distribution(
      app: "1:629899183939:android:b121b5f2c5f3e3f3e3f3e3",
      testers: "test@example.com",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_token: ENV["FIREBASE_TOKEN"]
    )
  end
end