name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Increment version
        run: ruby scripts/increment_patch_version.rb

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build and release Android
        run: |
          cd android/fastlane
          pwd
          bundle install
          bundle exec fastlane distribute

      - name: Build and release iOS
        run: |
          cd ios/fastlane
          pwd
          bundle install
          bundle exec fastlane distribute

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "chore: bump version"
          git push